name: main

on: [push, pull_request]

jobs:
  publish:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish View/ -o Sparky/bin/Publish/ --configuration Release --no-self-contained -r win-x64 -p:PublishSingleFile=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Sparky
        path: Sparky/bin/Publish/

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Sparky
          path: Sparky

      - name: Create package
        run: Compress-Archive -Path Sparky/*.exe -DestinationPath Sparky.zip -Force
        shell: pwsh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            [Changelog](https://github.com/xrAlex/Sparky/blob/main/Changelog.md)
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: Sparky.zip
          asset_path: Sparky.zip
          asset_content_type: application/zip
